CREATE DATABASE PRACTICE;
USE PRACTICE;
DROP TABLE AIRLINES;
CREATE TABLE AIRLINES(
	ID INT auto_increment PRIMARY KEY,
    NAMES VARCHAR(90)
)
auto_increment=100;

INSERT INTO AIRLINES(NAMES) VALUES
('AIR1'),
('AIR2'),
('AIR3'),
('AIR4'),
('AIR5'),
('AIR6'),
('AIR7'),
('AIR8'),
('AIR9');

SELECT * FROM AIRLINES;
INSERT INTO AIRLINES VALUES (20,'AIR20');
INSERT INTO AIRLINES(NAMES) VALUES ('AIR210');
INSERT INTO AIRLINES VALUES (200,'AIR200');
INSERT INTO AIRLINES VALUES (NULL,'AIR200');
INSERT INTO AIRLINES VALUES (0,'AIR00');

INSERT IGNORE INTO airlines VALUES  
(200, 'North Air'),    -- this row will be skipped as ID 200 already exists, and IGNORE option used 
(0, 'Emirates'),        -- id 203 is assigned 
(0, 'Qantas');  

SELECT last_insert_id();
 INSERT IGNORE INTO AIRLINES VALUES
 (NULL,'PP3');
INSERT IGNORE INTO airlines VALUES  
(200, 'North Air11111'),    
(0, 'Emirates1111'), 
(0, 'Qanta1s1111');
SELECT * FROM AIRLINES WHERE ID=206;
SET SQL_SAFE_UPDATES=0;
DELETE FROM AIRLINES;
SELECT * FROM AIRLINES;
INSERT INTO AIRLINES(NAMES)VALUES('PP_AIRZET');
ALTER TABLE AIRLINES auto_increment=20;

-- -----------------------------------------PRACTICE--------------------------------------------------
USE PRACTICE;
CREATE TABLE SNOWFLAKE_CUSTOMER
(
	C_CUSTKEY BIGINT,
	C_NAME	VARCHAR(100),
    C_ADDRESS	VARCHAR(100),
    C_NATIONKEY	VARCHAR(100),
    C_PHONE	VARCHAR(80),
    C_ACCTBAL	DECIMAL(10,2),
    C_MKTSEGMENT VARCHAR(100),	
    C_COMMENT VARCHAR(300)
);
SELECT COUNT(*) FROM SNOWFLAKE_CUSTOMER;
CREATE TABLE CUSTOMER_AUTO_INCRIMENT LIKE SNOWFLAKE_CUSTOMER;
DESCRIBE CUSTOMER_AUTO_INCRIMENT;
ALTER TABLE CUSTOMER_AUTO_INCRIMENT
ADD COLUMN ID INT PRIMARY KEY auto_increment;

INSERT INTO CUSTOMER_AUTO_INCRIMENT(C_CUSTKEY,  
C_NAME , 
C_ADDRESS , 
C_NATIONKEY , 
C_PHONE , 
C_ACCTBAL , 
C_MKTSEGMENT, 
C_COMMENT)
SELECT * FROM SNOWFLAKE_CUSTOMER;
SELECT * FROM  CUSTOMER_AUTO_INCRIMENT;
insert into CUSTOMER_AUTO_INCRIMENT(c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment)
values (219874, 'Customer#000219874', 'sadhjekj', 9, '19-505-461-2873', 999.99, 'asjdasgdj', 'sdadtyhkjer');

SELECT * FROM CUSTOMER_AUTO_INCRIMENT WHERE c_custkey=219874;


















