create or replace table PP_COLORS as
    select name
    from (values ('blue'),('red'),('green')) colors (name);
SELECT * FROM PP_COLORS;
-- Next we create a new table with the same structure as the existing table and add an idenity column.  

create or replace table PP_identity_column_example like PP_COLORS;

select * from PP_identity_column_example;
ALTER TABLE PP_identity_column_example
ADD COLUMN ID INT IDENTITY(1,3);
insert into PP_identity_column_example(name) 
    select name from PP_colors;
select * from PP_identity_column_example;

ALTER TABLE PP_identity_column_example RENAME TO COLORS;
SELECT * FROM COLORS;




DESCRIBE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE OR REPLACE TABLE PP_EXAMPLE_SEQUENCE LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

SELECT * FROM  PP_EXAMPLE_SEQUENCE;
DESCRIBE TABLE PP_EXAMPLE_SEQUENCE;

ALTER TABLE PP_EXAMPLE_SEQUENCE
ADD COLUMN ID INT IDENTITY(1,1);

INSERT INTO PP_EXAMPLE_SEQUENCE
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
--DROP TABLE PP_EXAMPLE_SEQUENCE;
--ALTER TABLE PP_EXAMPLE_SEQUENCE DROP COLUMN ID;
CREATE OR REPLACE SEQUENCE SEQ1 
START=1
INCREMENT=1;

DESCRIBE SEQUENCE SEQ1;

ALTER TABLE PP_EXAMPLE_SEQUENCE
ADD COLUMN ID INT DEFAULT SEQ1.NEXTVAL;

INSERT INTO PP_EXAMPLE_SEQUENCE
SELECT *,SEQ1.NEXTVAL FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

SELECT * FROM PP_EXAMPLE_SEQUENCE ORDER BY ID;

SELECT ID FROM PP_EXAMPLE_SEQUENCE ORDER BY ID;
insert into PP_EXAMPLE_SEQUENCE(c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment)
values (219874, 'Customer#000219874', 'sadhjekj', 9, '19-505-461-2873', 999.99, 'asjdasgdj', 'sdadtyhkjer');

select * from PP_EXAMPLE_SEQUENCE 
where c_custkey = 219874;
--order by id;
--------------------------------------------------PRACTICE STEP BY STEP  -----------------------------------------------------
DESCRIBE TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
CREATE OR REPLACE SEQUENCE SEQ_PRAC
START=1
INCREMENT=1
COMMENT='THIS IS THE SEQUENCE FOR PRACTICE';
DESCRIBE SEQUENCE SEQ_PRAC;

--CREATING A TABLE LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
CREATE OR REPLACE TABLE PP_SEQUENCE_PRACTICE LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
DESCRIBE TABLE PP_SEQUENCE_PRACTICE;
SELECT * FROM PP_SEQUENCE_PRACTICE;
ALTER TABLE PP_SEQUENCE_PRACTICE
ADD COLUMN ID INT DEFAULT SEQ_PRAC.NEXTVAL;

INSERT INTO PP_SEQUENCE_PRACTICE 
SELECT *,SEQ_PRAC.NEXTVAL FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;


SELECT * FROM PP_SEQUENCE_PRACTICE;
SELECT COUNT(DISTINCT ID) FROM PP_SEQUENCE_PRACTICE;
insert into PP_SEQUENCE_PRACTICE(c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment)
values (219874, 'Customer#000219874', 'sadhjekj', 9, '19-505-461-2873', 999.99, 'asjdasgdj', 'sdadtyhkjer');

SELECT * FROM PP_SEQUENCE_PRACTICE WHERE c_custkey=219874;
SELECT COUNT(*) FROM PP_SEQUENCE_PRACTICE;