USE DATABASE PRAVAT_DB;
SELECT * FROM PRAVAT_DB.PUBLIC.PP_CONSUMER_COMPLAINT;

--TO GET CURRENT DATE
SELECT CURRENT_DATE;
--TO GET CURRENT TIMESTAMP
SELECT CURRENT_TIMESTAMP;
/*
IT GAVE US 2024-08-25 04:51:30.625 -0700 AS OUTPUT WHERE 
-0700  indicates that the time is in a time zone that is 7 hours behind Coordinated Universal Time (UTC-07:00).
*/
--EXTRACTING ALL THE COMPONENTS FROM TIMESTAMP
SELECT 
    YEAR(CURRENT_TIMESTAMP) AS YEAR,
    MONTH(CURRENT_TIMESTAMP) AS MONTH,
    WEEK(CURRENT_TIMESTAMP) AS WEEK,
    DAY(CURRENT_TIMESTAMP) AS DAY,
    HOUR(CURRENT_TIMESTAMP) AS HOUR,
    MINUTE(CURRENT_TIMESTAMP) AS MINUTE,
    SECOND(CURRENT_TIMESTAMP) AS SECOND;
SELECT 
    TO_CHAR(CURRENT_TIMESTAMP, 'TZH:TZM') AS timezone_offset;--TO FIND THE OFFSET
-- TO FIND THE CURRENT TIMEZONE
SHOW PARAMETERS LIKE 'TIMEZONE' IN ACCOUNT;
SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

-- TO CONVERT TIMEZONE
SELECT CONVERT_TIMEZONE('America/Los_Angeles','UTC',CURRENT_TIMESTAMP) AS RESET_TIMEZONE;
SELECT TO_TIMESTAMP_LTZ(CURRENT_TIMESTAMP);
SELECT LOCALTIMESTAMP;



--TO FIND ANY DATE BEFORE TODAY OR AFTER TODAY
SELECT ADD_MONTHS(CURRENT_DATE,-2);
SELECT ADD_MONTHS(CURRENT_DATE,2):: DATE;

--TO FORMAT THE DATE-STYLE
SELECT TO_CHAR(CURRENT_DATE,'DD-MM-YYYY') AS DATE_STYLE;
SELECT TO_CHAR(CURRENT_DATE,'DD-MM-YY') AS DATE_STYLE;
SELECT TO_CHAR(CURRENT_DATE,'DD-MON-YYYY') AS DATE_STYLE;
SELECT TO_CHAR(CURRENT_DATE,'MM-DD-YYYY') AS DATE_STYLE;
SELECT TO_CHAR(CURRENT_DATE,'MM-DD-YY') AS DATE_STYLE;



--------------DATE_TRUNC--------------------
SELECT DATE_TRUNC('YEAR',CURRENT_DATE)AS YEAR;
SELECT DATE_TRUNC('MONTH',CURRENT_DATE)AS MONTH;
SELECT DATE_TRUNC('DAY',CURRENT_DATE)AS DAY;
SELECT DATE_TRUNC('WEEK',CURRENT_DATE)AS CURRENT_WEEK;-- GIVE US THE STARTING DATE OF THIS WEEK (MONDAY)


SELECT WEEK(CURRENT_DATE) AS WEEK_NO_FROM_START;

SELECT LAST_DAY('2024-08-10':: DATE) AS LAST_DATE_CURRENT_MONTH;
SELECT DATE_PART(DAYOFWEEK, '2024-08-10':: DATE);-- IT GIVES US THE DAY NO OF THE GIVEN DATE

SELECT LAST_DAY(CURRENT_DATE-INTERVAL'2 MONTHS')AS LAST_DAY_2MONTH_BEFORE;
SELECT LAST_DAY(CURRENT_DATE+INTERVAL'2 MONTHS')AS LAST_DAY_2MONTH_AFTER;

SELECT DAYNAME(CURRENT_DATE);
SELECT EXTRACT(MONTH FROM CURRENT_DATE);
SELECT EXTRACT(MONTH FROM '2024-10-21'::DATE);
SELECT QUARTER(CURRENT_DATE);


--------------------------DATEDIFF AND DATEADD ---------------------------------
SELECT DATEDIFF(MONTH,'2024-08-15','2024-09-23');
SELECT DATEADD(DAY,20,'2024-08-25');
SELECT DATEADD(MONTH,2,'2024-08-25');
SELECT DATEADD(YEAR,-2,'2024-08-25');
SELECT DATEADD(MONTH,-20,'2024-08-25');
SELECT DATEADD(DAY,5,'2024-08-25');

SELECT MONTHS_BETWEEN('2024-08-25'::DATE,'2024-10-25'::DATE);
SELECT DATEDIFF(MONTH,'2024-10-25','2024-08-25');

































    
