USE DATABASE PRAVAT_DB;
CREATE OR REPLACE TABLE PP_FIRST_TABLE(
    DATE_RECIEVED STRING,
    PRODUCT_NAME VARCHAR2(100),
    SUB_PRODUCT VARCHAR2(100),
    ISSUES VARCHAR2(150),
    SUB_ISSUE VARCHAR2(150),
    CONSUMER_COMPLAINT_NARRATIVE STRING,
    COMPANY_RESPONSE STRING,
    COMPANY VARCHAR(150),
    STATE_NAME VARCHAR(15),
    ZIPCODE STRING,
    CUSTOMER_TAG VARCHAR(100),
    CONSUMER_CONSENT_PROVIDER VARCHAR(100),
    SUBMITTED_VIA STRING,
    DATE_SENT_TO_COMPANY STRING,
    COMPANY_RESPONSE_CONSUMER VARCHAR(150),
    TIMELY_RESPONSED VARCHAR(50),
    CONSUMER_DISPUTED VARCHAR(101)
);
DESCRIBE TABLE PRAVAT_DB.PUBLIC.PP_FIRST_TABLE;

SELECT * FROM PRAVAT_DB.PUBLIC.PP_FIRST_TABLE;
SELECT CURRENT_DATE;
SELECT CURRENT_TIMESTAMP;

SELECT 
    DAY(CURRENT_TIMESTAMP)AS DAY,
    MONTH(CURRENT_TIMESTAMP) AS MONTH;
    
CREATE or replace table NJ_CONSUMER_COMPLAINTS

(    DATE_RECEIVED STRING,
     PRODUCT_NAME VARCHAR2(100),
     SUB_PRODUCT VARCHAR2(100),
     ISSUE VARCHAR2(100),
     SUB_ISSUE VARCHAR2(100),
     CONSUMER_COMPLAINT_NARRATIVE string,
     Company_Public_Response STRING,
     Company VARCHAR(100),
     State_Name CHAR(80),
     Zip_Code string,
     Tags VARCHAR(100),
     Consumer_Consent_Provided CHAR(100),
     Submitted_via STRING,
     Date_Sent_to_Company STRING,
     Company_Response_to_Consumer VARCHAR(100),
     Timely_Response CHAR(60),
     CONSUMER_DISPUTED CHAR(60),
     COMPLAINT_ID NUMBER(12,0) NOT NULL PRIMARY KEY
);

DESCRIBE TABLE NJ_CONSUMER_COMPLAINTS;
SELECT * FROM NJ_CONSUMER_COMPLAINTS;

------------------------------------------------------------------------------------------------------
--DATE AND TIME FUNCTION 
--1.FIND THE CURRENT DATE 
SELECT CURRENT_DATE AS TODAY;
SELECT DATE_TRUNC('MONTH',CURRENT_DATE) AS MONTH;
SELECT DATE_TRUNC('YEAR',CURRENT_DATE) AS MONTH;
SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS MONTH;
SELECT MONTH(TO_DATE('2024-07-21')) AS MONTH_NAME;
SELECT TO_CHAR(TO_DATE('2024-07-21'),'DD-MON-YY')AS TODAY_DATE;

SELECT DISTINCT PRODUCT_NAME FROM PRAVAT_DB.PUBLIC.NJ_CONSUMER_COMPLAINTS;
SELECT SUBMITTED_VIA,
CASE
    WHEN SUBMITTED_VIA IN ('Phone','Web') THEN 'Inbond'
    WHEN SUBMITTED_VIA IN ('Referral','postal mail','Email') THEN 'Outbond'
    ELSE 'Electronic'
END AS SUBMITTED_VIA_FLAG
FROM PRAVAT_DB.PUBLIC.NJ_CONSUMER_COMPLAINTS;

SELECT PRODUCT_NAME,
CASE
    WHEN PRODUCT_NAME IN ('Consumer Loan','Student loan','Payday loan') THEN 'LOAN'
    WHEN PRODUCT_NAME IN ('Bank account or service','Mortgage','Debt collection','Credit card','Credit reporting',
    'Money transfers','Prepaid card') THEN 'SERIVICE'
    ELSE 'OTHERS'
END AS LOAN_TYPE
FROM NJ_CONSUMER_COMPLAINTS;


