CREATE SCHEMA PRACTICE_ALL;
----------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE AGENT_PP LIKE PP_PRACTICE.PUBLIC.PP_AGENTS;
DESCRIBE TABLE AGENT_PP;

INSERT INTO AGENT_PP VALUES ('A003', 'Alex ', 'London', '0.13', '075-12458969', '');
INSERT INTO AGENT_PP VALUES ('A008', 'Alford', 'New York', '0.12', '044-25874365', '');
INSERT INTO AGENT_PP VALUES ('A011', 'Ravi Kumar', 'Bangalore', '0.15', '077-45625874', '');
INSERT INTO AGENT_PP VALUES ('A010', 'Santakumar', 'Chennai', '0.14', '007-22388644', '');
INSERT INTO AGENT_PP VALUES ('A012', 'Lucida', 'San Jose', '0.12', '044-52981425', '');
INSERT INTO AGENT_PP VALUES ('A005', 'Anderson', 'Brisban', '0.13', '045-21447739', '');
INSERT INTO AGENT_PP VALUES ('A001', 'Subbarao', 'Bangalore', '0.14', '077-12346674', '');
INSERT INTO AGENT_PP VALUES ('A002', 'Mukesh', 'Mumbai', '0.11', '029-12358964', '');
INSERT INTO AGENT_PP VALUES ('A006', 'McDen', 'London', '0.15', '078-22255588', '');
INSERT INTO AGENT_PP VALUES ('A004', 'Ivan', 'Torento', '0.15', '008-22544166', '');
INSERT INTO AGENT_PP VALUES ('A009', 'Benjamin', 'Hampshair', '0.11', '008-22536178', '');
INSERT INTO AGENT_PP VALUES ('A007', 'Ramasundar', 'Bangalore',0.15,'077-25814763', '');
INSERT INTO AGENT_PP(AGENT_CODE,AGENT_NAME,WORKING_AREA)VALUES ('A110', 'Anand', 'Germany');

SELECT * FROM AGENT_PP;

------UPDATION-------------------------
UPDATE AGENT_PP SET COUNTRY='INDIA' WHERE COUNTRY ='' OR COUNTRY IS NULL;

----------------------------------SUBSTRING---------------------------------------------------------
SELECT SUBSTR('PRAVAT PATRA',3,6);
SELECT SUBSTRING('PRAVAT PATRA',3,6);
-----USE CASE ------------------------------------------------
--Q. I WANT TO EXTRACT LAST TWO NUMBER FROM AGENT CODE.THERE IS VERIOUS WAY TO DO THAT ONE OF THEN  IS SUBSTRING.
SELECT AGENT_CODE,SUBSTR(AGENT_CODE,-2,2) AS AGENT_NO FROM AGENT_PP;

--2.TRIM FUCNTION 
SELECT TRIM('        PRAVAT            ');
SELECT LENGTH(TRIM('        PRAVAT            ')); --OR
SELECT LEN(TRIM('        PRAVAT            '));
-- FIND THE AVERAGE LENGTH OF NAME OF AGENT
SELECT AVG(LENGTH(TRIM(AGENT_NAME))) AS AVERAGE_LEN_NAME FROM AGENT_PP;

-------------------------------CONCAT------------------------------------------------------------------
SELECT CONCAT('PRAVAT ',NULL);--CONCAT ANYTHING WITH NULL GIVES NULL AS RESULT
SELECT AGENT_CODE,AGENT_NAME,CONCAT(AGENT_CODE,'-',AGENT_NAME) AS AGENT_DETAILS FROM AGENT_PP;
--OTHER WAY
SELECT AGENT_CODE,AGENT_NAME,AGENT_CODE||'-'||AGENT_NAME AS AGENT_DETAILS FROM AGENT_PP;

--CONCAT WITH SEPARATOR -CONCAT_WS
SELECT AGENT_CODE,AGENT_NAME,CONCAT_WS('-',AGENT_CODE,AGENT_NAME,WORKING_AREA) AS AGENT_DETAILS FROM AGENT_PP;

--CAST AND TRY_CAST
SELECT CAST('2024-10-21'AS DATE);
SELECT '2024-10-09'::DATE;

SELECT CAST('2024-10-33'AS DATE);--GIVES AN ERROR
SELECT TRY_CAST('2024-10-33'AS DATE);--OUTPUT-NULL

--REVERSE
SELECT REVERSE('PRAVAT PATRA') AS REV_NAME;

SELECT SPLIT('2021.23.34.34','.');
SELECT SPLIT('20-20-40','-');

SELECT SPLIT_PART('1021-21-52','-',1);
SELECT SPLIT_PART('1021-21-52','-',2);
SELECT SPLIT_PART('1021-21-52','-',3);
SELECT SPLIT_PART('1021-21-52','-',5);--NO OUTPUT

--REPLACE
SELECT AGENT_CODE,REPLACE(AGENT_CODE,0,'*')AS NEW_STYLE FROM AGENT_PP;
-------------------------------------PART 2---------------------------------------------------------
--1.LATERAL FLATTEN
CREATE OR REPLACE TABLE PP_FAMILY(
    PARENT VARCHAR(20),
    CHILDREN VARCHAR(40)
);

INSERT INTO PP_FAMILY VALUES
('ROHIT','BABAR,HARIS,AFRIDI'),
('VIRAT','CUMMINS,HAZAL,ZAMPA');

SELECT * FROM PP_FAMILY;
--************************************************************************************
SELECT PARENT,A.VALUE :: STRING AS CHILDNAME
FROM PP_FAMILY,LATERAL FLATTEN(SPLIT(CHILDREN,','))A;

--INITCAP
SELECT INITCAP('I AM PRAVAT','');-- DELIMETER
SELECT INITCAP('I AM PRAVAT+PATRA','+ ');--DELEMETER SET

--REPLACE
SELECT REPLACE('   T  E S T I N G 1 2 3 4   ',' ');
SELECT REPLACE('P R A V A T ',' ','*');

--NVL

INSERT INTO PP_FAMILY VALUES
(NULL,'C1'),
('P1','C2'),
('P2','C3'),
(NULL,'C1'),
('P6','C5'),
(NULL,'C7');

SELECT * FROM PP_FAMILY;

SELECT PARENT,NVL(PARENT,'NO PARENT') AS PARENT_STATUS FROM PP_FAMILY;
--SELECT PARENT,REPLACE(PARENT,'P','NO PARENT') AS PARENT_STATUS FROM PP_FAMILY;
--SELECT AGENT_CODE,REPLACE(AGENT_CODE,0,'*')AS NEW_STYLE FROM AGENT_PP;
--WE CQAN'T ALWAYS USE REPLACE
--COALESE
CREATE OR REPLACE TABLE PP_DETAILS
(
    NAME VARCHAR(10),
    VOTER_CARD VARCHAR(10),
    ADHAR_CARD VARCHAR(10),
    PAN_CARD VARCHAR(10)
);

INSERT INTO PP_DETAILS VALUES
('PRAVAT',NULL,'A001','P001'),
('ROHIT','V001',NULL,NULL),
(NULL,'V001',NULL,'P002'),
(NULL,NULL,NULL,'P001'),
('VIRAT',NULL,'V004','P007'),
(NULL,NULL,'V001',NULL);

SELECT * FROM PP_DETAILS;

SELECT *,COALESCE(NAME,VOTER_CARD,ADHAR_CARD,PAN_CARD) AS CONTACT_DETAILS FROM PP_DETAILS;

--CONTAINS() FUNCTION
CREATE OR REPLACE TABLE PP_COMMENT
(
    NAME VARCHAR(10),
    COMMENT_ STRING
);
INSERT INTO PP_COMMENT VALUES
('PRAVAT','HEY MACHINE LEARNING IS THE BEST'),
('SIVHAM','HEY MACHINE LEARNING IS NOT BEST'),
('ROHIT','CRICKET IS BEST'),
('PANCHA','LINUX IS BEST'),
('SIKHAR','DEEP LEARNING IS BEST');

SELECT * FROM PP_COMMENT;

SELECT * ,CONTAINS(COMMENT_,'MACHINE LEARNING') AS ML FROM PP_COMMENT;
SELECT * FROM PP_COMMENT WHERE CONTAINS(COMMENT_,'MACHINE LEARNING')=TRUE;

































































































































































